### ISSUE TITLE
Fitaly keyboard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [diarydarbanyusa/softkeyboard#189]
```
I've been a fan of this layout since my Palm Pilot 5000 days.

http://fitaly.com/fitaly/fitaly.htm

I'd create it myself if I could only figure out how.
```

Original issue reported on code.google.com by `masieg...@gmail.com` on 18 Nov 2009 at 7:39
- Blocking: #190

**Comment by CmputrAce** [comment]
The patent for the Fitaly layout has expired. Jan 1996 is the patent date, an design patents are valid for 14 years. Process patents are valid for 20. either way, it's expired.
